// Generated by gencpp from file darknet_ros_zed/coordinate_msgs.msg
// DO NOT EDIT!


#ifndef DARKNET_ROS_ZED_MESSAGE_COORDINATE_MSGS_H
#define DARKNET_ROS_ZED_MESSAGE_COORDINATE_MSGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace darknet_ros_zed
{
template <class ContainerAllocator>
struct coordinate_msgs_
{
  typedef coordinate_msgs_<ContainerAllocator> Type;

  coordinate_msgs_()
    : x(0.0)
    , y(0.0)
    , depth(0.0)
    , probability(0.0)
    , className()  {
    }
  coordinate_msgs_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , depth(0.0)
    , probability(0.0)
    , className(_alloc)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _depth_type;
  _depth_type depth;

   typedef double _probability_type;
  _probability_type probability;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _className_type;
  _className_type className;





  typedef boost::shared_ptr< ::darknet_ros_zed::coordinate_msgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::darknet_ros_zed::coordinate_msgs_<ContainerAllocator> const> ConstPtr;

}; // struct coordinate_msgs_

typedef ::darknet_ros_zed::coordinate_msgs_<std::allocator<void> > coordinate_msgs;

typedef boost::shared_ptr< ::darknet_ros_zed::coordinate_msgs > coordinate_msgsPtr;
typedef boost::shared_ptr< ::darknet_ros_zed::coordinate_msgs const> coordinate_msgsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::darknet_ros_zed::coordinate_msgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::darknet_ros_zed::coordinate_msgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace darknet_ros_zed

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'darknet_ros_zed': ['/home/chen/qtProjects/catkin_ws_darknet_ros_zed/src/darknet_ros_zed/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::darknet_ros_zed::coordinate_msgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::darknet_ros_zed::coordinate_msgs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_ros_zed::coordinate_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_ros_zed::coordinate_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_ros_zed::coordinate_msgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_ros_zed::coordinate_msgs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::darknet_ros_zed::coordinate_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2020fc069dbb4fb7790c96426024b2f9";
  }

  static const char* value(const ::darknet_ros_zed::coordinate_msgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2020fc069dbb4fb7ULL;
  static const uint64_t static_value2 = 0x790c96426024b2f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::darknet_ros_zed::coordinate_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "darknet_ros_zed/coordinate_msgs";
  }

  static const char* value(const ::darknet_ros_zed::coordinate_msgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::darknet_ros_zed::coordinate_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 depth\n\
float64 probability\n\
string className\n\
";
  }

  static const char* value(const ::darknet_ros_zed::coordinate_msgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::darknet_ros_zed::coordinate_msgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.depth);
      stream.next(m.probability);
      stream.next(m.className);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct coordinate_msgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::darknet_ros_zed::coordinate_msgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::darknet_ros_zed::coordinate_msgs_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "depth: ";
    Printer<double>::stream(s, indent + "  ", v.depth);
    s << indent << "probability: ";
    Printer<double>::stream(s, indent + "  ", v.probability);
    s << indent << "className: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.className);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DARKNET_ROS_ZED_MESSAGE_COORDINATE_MSGS_H
